import { useEffect, useRef, useState, type PointerEvent as ReactPointerEvent } from 'react'
import type { CleanupDiagnosticComponent } from './brushCleanup'
import type { Point } from './EntranceSelector'

type Props = { imageSrc: string; components: CleanupDiagnosticComponent[]; centers: Point[]; onCentersChange: (centers: Point[]) => void }

export function CleanupSampleAdjuster({ imageSrc, components, centers, onCentersChange }: Props) {
  const editorRef = useRef<HTMLDivElement>(null); const stageRef = useRef<HTMLDivElement>(null); const naturalRef = useRef({ width: 0, height: 0 }); const dragRef = useRef<{ index: number; pointer: number } | null>(null); const [size, setSize] = useState({ width: 0, height: 0 })
  const resize = () => { const bounds = editorRef.current?.getBoundingClientRect(); const natural = naturalRef.current; if (!bounds || !natural.width) return; const scale = Math.min(bounds.width / natural.width, bounds.height / natural.height); setSize({ width: natural.width * scale, height: natural.height * scale }) }
  useEffect(() => { const observer = new ResizeObserver(resize); if (editorRef.current) observer.observe(editorRef.current); return () => observer.disconnect() }, [])
  const point = (event: ReactPointerEvent): Point | null => { const bounds = stageRef.current?.getBoundingClientRect(); if (!bounds) return null; return { x: Math.max(0, Math.min(1, (event.clientX - bounds.left) / bounds.width)), y: Math.max(0, Math.min(1, (event.clientY - bounds.top) / bounds.height)) } }
  const move = (event: ReactPointerEvent) => { const drag = dragRef.current; const next = point(event); if (!drag || drag.pointer !== event.pointerId || !next) return; const values = [...centers]; values[drag.index] = next; onCentersChange(values) }
  return <div ref={editorRef} className="visualizer-editor cleanup-sample-editor" aria-label="Adjust cleanup sample areas"><div ref={stageRef} className="entrance-image-stage cleanup-sample-stage" style={size.width ? { width:size.width,height:size.height }:undefined} onPointerMove={move} onPointerUp={() => { dragRef.current = null }} onPointerCancel={() => { dragRef.current = null }}><img src={imageSrc} alt="Original photo with cleanup target and sample markers" onLoad={(event) => { naturalRef.current={width:event.currentTarget.naturalWidth,height:event.currentTarget.naturalHeight};resize() }}/>{size.width>0&&components.map((component,index)=>{const center=centers[index];if(!center)return null;const scaleX=size.width/naturalRef.current.width;const scaleY=size.height/naturalRef.current.height;return <div key={index}><span className="cleanup-target-box" style={{left:component.destination.x*scaleX,top:component.destination.y*scaleY,width:component.destination.width*scaleX,height:component.destination.height*scaleY}}/><button type="button" className="cleanup-sample-marker" aria-label={`Move sample area ${index+1}`} style={{left:`${center.x*100}%`,top:`${center.y*100}%`,width:Math.max(28,component.destination.width*scaleX),height:Math.max(28,component.destination.height*scaleY)}} onPointerDown={(event)=>{event.preventDefault();stageRef.current?.setPointerCapture(event.pointerId);dragRef.current={index,pointer:event.pointerId}}}>Sample {index+1}</button></div>})}</div></div>
}
