import { useEffect, useId, useRef, useState, type PointerEvent as ReactPointerEvent } from 'react'
import { MinusCircle, Move, PlusCircle, RotateCcw, ZoomIn, ZoomOut } from 'lucide-react'
import type { CleanupStroke } from './CleanupBrushEditor'
import { isValidEntranceCorners, type CornerId, type EntranceCorners, type Point } from './EntranceSelector'
import type { FrameMaskCorrections, FrameSides } from './frameRecolor'
import { usePhotoZoom } from './usePhotoZoom'
import { emptySnapState, freeDragWithMagneticSnap, type SnapGuides, type SnapState } from './magneticSnap'

const ORDER: CornerId[] = ['topLeft', 'topRight', 'bottomRight', 'bottomLeft']
const MAGNIFIER_ZOOM = 2
const MAGNIFIER_SIZE = 132
const MOBILE_MAGNIFIER_SIZE = 90
type Tool = 'adjust' | 'add' | 'remove'
type Props = { imageSrc: string; inner: EntranceCorners; openings?: EntranceCorners[]; outer: EntranceCorners; sides: FrameSides; corrections: FrameMaskCorrections; wizardMode?: boolean; editable?: boolean; onImageSize?: (size:{width:number;height:number})=>void; onOuterChange: (value: EntranceCorners) => void; onSidesChange: (value: FrameSides) => void; onCorrectionsChange: (value: FrameMaskCorrections) => void; onReset: () => void; onConfirm: () => void }

export function FrameAreaEditor({ imageSrc, inner, openings = [inner], outer, sides, corrections, wizardMode = false, editable = true, onImageSize, onOuterChange, onSidesChange, onCorrectionsChange, onReset, onConfirm }: Props) {
  const editorRef=useRef<HTMLDivElement>(null),stageRef=useRef<HTMLDivElement>(null),naturalRef=useRef({width:0,height:0}),dragRef=useRef<{id?:CornerId;pointer:number;stroke?:CleanupStroke}|null>(null),magnifierDragRef=useRef<number|null>(null),snapRef=useRef<SnapState>(emptySnapState())
  const [size,setSize]=useState({width:0,height:0}),[tool,setTool]=useState<Tool>('adjust'),[cursor,setCursor]=useState<Point|null>(null),[activeCorner,setActiveCorner]=useState<CornerId|null>(null),[magnifierPosition,setMagnifierPosition]=useState(()=>typeof window!=='undefined'&&window.matchMedia('(max-width: 767px)').matches?{x:.17,y:.78}:{x:.17,y:.5}),[snapGuides,setSnapGuides]=useState<SnapGuides>({})
  const magnifierSize=typeof window!=='undefined'&&window.matchMedia('(max-width: 767px)').matches?MOBILE_MAGNIFIER_SIZE:MAGNIFIER_SIZE
  const maskId=`frame-area-mask-${useId().replace(/:/g,'')}`
  const {zoom,pan,isPanning,onWheel,beginPan,movePan,endPan,zoomIn,zoomOut,resetZoom}=usePhotoZoom(editorRef,size)
  useEffect(resetZoom,[imageSrc,resetZoom])
  const resize=()=>{const bounds=editorRef.current?.getBoundingClientRect(),natural=naturalRef.current;if(!bounds||!natural.width)return;const scale=Math.min(bounds.width/natural.width,bounds.height/natural.height),next={width:natural.width*scale,height:natural.height*scale};setSize(next)}
  useEffect(()=>{const observer=new ResizeObserver(resize);if(editorRef.current)observer.observe(editorRef.current);return()=>observer.disconnect()},[])
  const point=(event:ReactPointerEvent):Point|null=>{const bounds=stageRef.current?.getBoundingClientRect();if(!bounds)return null;return{x:Math.max(0,Math.min(1,(event.clientX-bounds.left)/bounds.width)),y:Math.max(0,Math.min(1,(event.clientY-bounds.top)/bounds.height))}}
  const downCorner=(id:CornerId,event:ReactPointerEvent)=>{event.preventDefault();stageRef.current?.setPointerCapture(event.pointerId);dragRef.current={id,pointer:event.pointerId};snapRef.current=emptySnapState();setActiveCorner(id)}
  const downBrush=(event:ReactPointerEvent<HTMLDivElement>)=>{if(tool==='adjust')return;const p=point(event);if(!p)return;event.preventDefault();event.currentTarget.setPointerCapture(event.pointerId);const stroke={points:[p],radius:.012};dragRef.current={pointer:event.pointerId,stroke};const key=tool==='add'?'add':'remove';onCorrectionsChange({...corrections,[key]:[...corrections[key],stroke]})}
  const move=(event:ReactPointerEvent<HTMLDivElement>)=>{const p=point(event);setCursor(p);const drag=dragRef.current;if(!p||!drag||drag.pointer!==event.pointerId)return;if(drag.id){const snapped=freeDragWithMagneticSnap(outer,drag.id,p,size,snapRef.current,event.shiftKey);snapRef.current=snapped.state;setSnapGuides(snapped.guides);const candidate={...outer,[drag.id]:snapped.point};const contains=candidate.topLeft.x<=inner.topLeft.x&&candidate.topLeft.y<=inner.topLeft.y&&candidate.topRight.x>=inner.topRight.x&&candidate.topRight.y<=inner.topRight.y&&candidate.bottomLeft.x<=inner.bottomLeft.x&&candidate.bottomLeft.y>=inner.bottomLeft.y&&candidate.bottomRight.x>=inner.bottomRight.x&&candidate.bottomRight.y>=inner.bottomRight.y;if(contains&&isValidEntranceCorners(candidate))onOuterChange(candidate)}else if(drag.stroke){const next={...drag.stroke,points:[...drag.stroke.points,p]};drag.stroke=next;const key=tool==='add'?'add':'remove';onCorrectionsChange({...corrections,[key]:[...corrections[key].slice(0,-1),next]})}}
  const points=(ids:CornerId[],value:EntranceCorners)=>ids.map(id=>`${value[id].x*size.width},${value[id].y*size.height}`).join(' ')
  const polygon=(value:EntranceCorners)=>points(ORDER,value)
  const strokePath=(stroke:CleanupStroke)=>stroke.points.map((p,i)=>`${i?'L':'M'}${p.x*size.width},${p.y*size.height}`).join(' ')
  const moveMagnifier=(event:ReactPointerEvent<HTMLButtonElement>)=>{if(magnifierDragRef.current!==event.pointerId)return;const bounds=editorRef.current?.getBoundingClientRect();if(!bounds)return;const insetX=Math.min(.45,magnifierSize/2/Math.max(1,bounds.width)),insetY=Math.min(.45,magnifierSize/2/Math.max(1,bounds.height));setMagnifierPosition({x:Math.max(insetX,Math.min(1-insetX,(event.clientX-bounds.left)/bounds.width)),y:Math.max(insetY,Math.min(1-insetY,(event.clientY-bounds.top)/bounds.height))})}
  const endMagnifierDrag=(event:ReactPointerEvent<HTMLButtonElement>)=>{if(magnifierDragRef.current!==event.pointerId)return;if(event.currentTarget.hasPointerCapture(event.pointerId))event.currentTarget.releasePointerCapture(event.pointerId);magnifierDragRef.current=null}
  const tools=<div className="frame-tool-controls"><button className={tool==='add'?'active':''} onClick={()=>setTool('add')}><PlusCircle size={16}/> Add to Frame Area</button><button className={tool==='remove'?'active':''} onClick={()=>setTool('remove')}><MinusCircle size={16}/> Remove from Frame Area</button><button onClick={onReset}><RotateCcw size={16}/> Reset Frame Area</button></div>
  return <section className="frame-area-workspace">
    {!wizardMode&&<div className="frame-area-heading"><h3>Define Jamb &amp; Frame</h3><p>Adjust the outside boundary of the photographed frame.</p></div>}
    {editable&&<div className="frame-side-toggles">{(wizardMode?[['bottom','Include Threshold']]as const:[['top','Top Frame'],['left','Left Frame'],['right','Right Frame'],['bottom','Bottom / Threshold']]as const).map(([key,label])=><label key={key}><input type="checkbox" checked={sides[key]} onChange={event=>onSidesChange({...sides,[key]:event.target.checked})}/> {label}</label>)}</div>}
    {editable&&(wizardMode?<details className="frame-fine-tune"><summary>Fine-Tune Frame Area</summary>{tools}</details>:tools)}
    <div ref={editorRef} className="visualizer-editor frame-area-editor">
      {editable&&tool==='adjust'&&activeCorner&&size.width>0&&<button type="button" className="entrance-point-magnifier" aria-label="Drag to move the frame corner magnifier" style={{width:magnifierSize,height:magnifierSize,left:`${magnifierPosition.x*100}%`,top:`${magnifierPosition.y*100}%`,bottom:'auto',backgroundImage:`url(${JSON.stringify(imageSrc)})`,backgroundSize:`${size.width*MAGNIFIER_ZOOM}px ${size.height*MAGNIFIER_ZOOM}px`,backgroundPosition:`${magnifierSize/2-outer[activeCorner].x*size.width*MAGNIFIER_ZOOM}px ${magnifierSize/2-outer[activeCorner].y*size.height*MAGNIFIER_ZOOM}px`}} onPointerDown={event=>{event.preventDefault();event.stopPropagation();event.currentTarget.setPointerCapture(event.pointerId);magnifierDragRef.current=event.pointerId}} onPointerMove={moveMagnifier} onPointerUp={endMagnifierDrag} onPointerCancel={endMagnifierDrag} onKeyDown={event=>{if(event.key.startsWith('Arrow'))event.preventDefault();const step=event.shiftKey?.06:.025;if(event.key==='ArrowLeft')setMagnifierPosition(value=>({...value,x:Math.max(.08,value.x-step)}));if(event.key==='ArrowRight')setMagnifierPosition(value=>({...value,x:Math.min(.92,value.x+step)}));if(event.key==='ArrowUp')setMagnifierPosition(value=>({...value,y:Math.max(.08,value.y-step)}));if(event.key==='ArrowDown')setMagnifierPosition(value=>({...value,y:Math.min(.92,value.y+step)}))}}><span className="entrance-magnifier-zoom">2×</span><span className="entrance-magnifier-move"><Move size={13}/></span><i/></button>}
      <div ref={stageRef} className={`entrance-image-stage frame-area-stage tool-${tool} ${zoom>1&&tool==='adjust'?'photo-pan-enabled':''} ${isPanning?'photo-panning':''}`} style={size.width?{width:size.width,height:size.height,transform:`translate(${pan.x}px, ${pan.y}px) scale(${zoom})`}:undefined} onPointerDown={event=>{if(tool==='adjust'&&event.target===event.currentTarget)beginPan(event);else downBrush(event)}} onPointerMove={event=>{if(!movePan(event))move(event)}} onPointerUp={event=>{endPan(event);dragRef.current=null;snapRef.current=emptySnapState();setSnapGuides({})}} onPointerCancel={event=>{endPan(event);dragRef.current=null;snapRef.current=emptySnapState();setSnapGuides({})}} onPointerLeave={()=>setCursor(null)} onWheel={onWheel}>
      <img src={imageSrc} alt="Uploaded entrance with proposed frame mask" onLoad={event=>{naturalRef.current={width:event.currentTarget.naturalWidth,height:event.currentTarget.naturalHeight};onImageSize?.(naturalRef.current);resize()}}/>
      {editable&&size.width>0&&<svg className="frame-mask-svg" viewBox={`0 0 ${size.width} ${size.height}`}>
        <defs><mask id={maskId} maskUnits="userSpaceOnUse" x="0" y="0" width={size.width} height={size.height}><rect width={size.width} height={size.height} fill="black"/><polygon points={polygon(outer)} fill="white"/>{openings.map((opening,index)=><polygon key={`opening-${index}`} points={polygon(opening)} fill="black"/>)}{!sides.bottom&&<polygon points={`${points(['bottomLeft','bottomRight'],outer)} ${points(['bottomRight','bottomLeft'],inner)}`} fill="black"/>}{corrections.add.map((stroke,index)=><path key={`mask-add-${index}`} d={strokePath(stroke)} fill="none" stroke="white" strokeLinecap="round" strokeLinejoin="round" strokeWidth={stroke.radius*Math.min(size.width,size.height)*2}/>)}{corrections.remove.map((stroke,index)=><path key={`mask-remove-${index}`} d={strokePath(stroke)} fill="none" stroke="black" strokeLinecap="round" strokeLinejoin="round" strokeWidth={stroke.radius*Math.min(size.width,size.height)*2}/>)}</mask></defs>
        <rect className="frame-mask-complete" width={size.width} height={size.height} mask={`url(#${maskId})`}/>
        {snapGuides.x!==undefined&&<line className="magnetic-snap-guide" x1={snapGuides.x*size.width} y1="0" x2={snapGuides.x*size.width} y2={size.height}/>} {snapGuides.y!==undefined&&<line className="magnetic-snap-guide" x1="0" y1={snapGuides.y*size.height} x2={size.width} y2={snapGuides.y*size.height}/>} {snapGuides.line&&<line className="magnetic-snap-guide" x1={snapGuides.line[0].x*size.width} y1={snapGuides.line[0].y*size.height} x2={snapGuides.line[1].x*size.width} y2={snapGuides.line[1].y*size.height}/>}
      </svg>}
      {editable&&tool==='adjust'&&ORDER.map(id=><button key={id} type="button" className="frame-corner-handle" aria-label={`Adjust outer frame ${id}`} style={{left:`${outer[id].x*100}%`,top:`${outer[id].y*100}%`}} onPointerDown={event=>downCorner(id,event)}/>)}{editable&&tool!=='adjust'&&cursor&&<span className="frame-brush-cursor" style={{left:`${cursor.x*100}%`,top:`${cursor.y*100}%`}}/>}
    </div><div className="visualizer-zoom-controls" role="group" aria-label="Uploaded photo zoom controls"><button type="button" aria-label="Zoom uploaded photo out" disabled={zoom<=1} onClick={zoomOut}><ZoomOut size={17}/></button><span aria-live="polite">{Math.round(zoom*100)}%</span><button type="button" aria-label="Zoom uploaded photo in" disabled={zoom>=4} onClick={zoomIn}><ZoomIn size={17}/></button><button type="button" onClick={resetZoom}>Reset Zoom</button></div></div>
    <div className="visualizer-zoom-controls mobile-external-zoom-controls" role="group" aria-label="Uploaded photo zoom controls"><button type="button" aria-label="Zoom uploaded photo out" disabled={zoom<=1} onClick={zoomOut}><ZoomOut size={17}/></button><span aria-live="polite">{Math.round(zoom*100)}%</span><button type="button" aria-label="Zoom uploaded photo in" disabled={zoom>=4} onClick={zoomIn}><ZoomIn size={17}/></button><button type="button" onClick={resetZoom}>Reset Zoom</button></div>
    {!wizardMode&&<button type="button" className="visualizer-apply-button" onClick={onConfirm}>Confirm Frame Area</button>}
  </section>
}
