import { useEffect, useRef, useState, type PointerEvent as ReactPointerEvent } from 'react'
import { Move, ZoomIn, ZoomOut } from 'lucide-react'
import { isValidEntranceCorners, type CornerId, type EntranceCorners, type Point } from './EntranceSelector'
import { usePhotoZoom } from './usePhotoZoom'
import { emptySnapState, freeDragWithMagneticSnap, type SnapGuides, type SnapState } from './magneticSnap'

export type SideliteSide = 'left' | 'right'
export type SideliteOpening = { innerTop: Point; innerBottom: Point; outerTop: Point; outerBottom: Point }
export type SideliteEdges = { left?: SideliteOpening; right?: SideliteOpening }
type Handle = keyof SideliteOpening
const MAGNIFIER_ZOOM=3
const MAGNIFIER_SIZE=132
const MOBILE_MAGNIFIER_SIZE=90
const CORNER_ORDER:CornerId[]=['topLeft','topRight','bottomRight','bottomLeft']
const cornerForHandle=(side:SideliteSide,handle:Handle):CornerId=>side==='left'?(handle==='outerTop'?'topLeft':handle==='innerTop'?'topRight':handle==='innerBottom'?'bottomRight':'bottomLeft'):(handle==='innerTop'?'topLeft':handle==='outerTop'?'topRight':handle==='outerBottom'?'bottomRight':'bottomLeft')

export function initializeSideliteEdges(door: EntranceCorners, sides: SideliteSide[]): SideliteEdges {
  const topWidth=door.topRight.x-door.topLeft.x,bottomWidth=door.bottomRight.x-door.bottomLeft.x
  const topGap=Math.max(.012,Math.min(.06,topWidth*.05)),bottomGap=Math.max(.012,Math.min(.06,bottomWidth*.05))
  return {
    ...(sides.includes('left')?{left:{innerTop:{x:Math.max(0,door.topLeft.x-topGap),y:door.topLeft.y},innerBottom:{x:Math.max(0,door.bottomLeft.x-bottomGap),y:door.bottomLeft.y},outerTop:{x:Math.max(0,door.topLeft.x-topGap-.15),y:door.topLeft.y},outerBottom:{x:Math.max(0,door.bottomLeft.x-bottomGap-.17),y:door.bottomLeft.y}}}:{}),
    ...(sides.includes('right')?{right:{innerTop:{x:Math.min(1,door.topRight.x+topGap),y:door.topRight.y},innerBottom:{x:Math.min(1,door.bottomRight.x+bottomGap),y:door.bottomRight.y},outerTop:{x:Math.min(1,door.topRight.x+topGap+.15),y:door.topRight.y},outerBottom:{x:Math.min(1,door.bottomRight.x+bottomGap+.17),y:door.bottomRight.y}}}:{})
  }
}

export function sideliteQuadrilateral(side:SideliteSide,opening:SideliteOpening):EntranceCorners{
  return side==='left'?{topLeft:opening.outerTop,topRight:opening.innerTop,bottomRight:opening.innerBottom,bottomLeft:opening.outerBottom}:{topLeft:opening.innerTop,topRight:opening.outerTop,bottomRight:opening.outerBottom,bottomLeft:opening.innerBottom}
}
export function sideliteOpeningQuads(edges:SideliteEdges){return(['left','right']as SideliteSide[]).flatMap(side=>edges[side]?[sideliteQuadrilateral(side,edges[side]!)]:[])}
export function completeEntranceBoundary(door:EntranceCorners,edges:SideliteEdges):EntranceCorners{return{topLeft:edges.left?.outerTop??door.topLeft,topRight:edges.right?.outerTop??door.topRight,bottomRight:edges.right?.outerBottom??door.bottomRight,bottomLeft:edges.left?.outerBottom??door.bottomLeft}}
export function dividerJambQuads(door:EntranceCorners,edges:SideliteEdges):EntranceCorners[]{const result:EntranceCorners[]=[];if(edges.left)result.push({topLeft:edges.left.innerTop,topRight:door.topLeft,bottomRight:door.bottomLeft,bottomLeft:edges.left.innerBottom});if(edges.right)result.push({topLeft:door.topRight,topRight:edges.right.innerTop,bottomRight:edges.right.innerBottom,bottomLeft:door.bottomRight});return result}

type Props={imageSrc:string;door:EntranceCorners;edges:SideliteEdges;sides:SideliteSide[];showSideChoice?:boolean;onChooseSide?:(side:SideliteSide)=>void;onChange:(edges:SideliteEdges)=>void}
export function SideliteSelector({imageSrc,door,edges,sides,showSideChoice=false,onChooseSide,onChange}:Props){
  const editorRef=useRef<HTMLDivElement>(null),stageRef=useRef<HTMLDivElement>(null),naturalRef=useRef({width:0,height:0}),dragRef=useRef<{side:SideliteSide;handle:Handle;pointer:number;corner:CornerId}|null>(null),magnifierDragRef=useRef<number|null>(null),pendingEdgesRef=useRef<SideliteEdges|null>(null),edgeFrameRef=useRef<number|null>(null),snapRef=useRef<SnapState>(emptySnapState());const[size,setSize]=useState({width:0,height:0}),[activeHandle,setActiveHandle]=useState<{side:SideliteSide;handle:Handle}|null>(null),[magnifierPosition,setMagnifierPosition]=useState(()=>typeof window!=='undefined'&&window.matchMedia('(max-width: 767px)').matches?{x:.25,y:.72}:{x:.17,y:.5}),[snapGuides,setSnapGuides]=useState<SnapGuides>({}),[alignedEdges,setAlignedEdges]=useState<Record<SideliteSide,Set<number>>>(()=>({left:new Set(),right:new Set()}))
  const magnifierSize=typeof window!=='undefined'&&window.matchMedia('(max-width: 767px)').matches?MOBILE_MAGNIFIER_SIZE:MAGNIFIER_SIZE
  const {zoom,pan,isPanning,onWheel,beginPan,movePan,endPan,zoomIn,zoomOut,resetZoom}=usePhotoZoom(editorRef,size)
  useEffect(resetZoom,[imageSrc,resetZoom])
  const resize=()=>{const bounds=editorRef.current?.getBoundingClientRect(),natural=naturalRef.current;if(!bounds||!natural.width)return;const scale=Math.min(bounds.width/natural.width,bounds.height/natural.height);setSize({width:natural.width*scale,height:natural.height*scale})};useEffect(()=>{const observer=new ResizeObserver(resize);if(editorRef.current)observer.observe(editorRef.current);return()=>observer.disconnect()},[])
  const point=(event:ReactPointerEvent):Point|null=>{const bounds=stageRef.current?.getBoundingClientRect();if(!bounds)return null;return{x:Math.max(0,Math.min(1,(event.clientX-bounds.left)/bounds.width)),y:Math.max(0,Math.min(1,(event.clientY-bounds.top)/bounds.height))}}
  useEffect(()=>()=>{if(edgeFrameRef.current!==null)cancelAnimationFrame(edgeFrameRef.current)},[])
  const scheduleEdgesChange=(nextEdges:SideliteEdges)=>{pendingEdgesRef.current=nextEdges;if(edgeFrameRef.current!==null)return;edgeFrameRef.current=requestAnimationFrame(()=>{edgeFrameRef.current=null;const pending=pendingEdgesRef.current;pendingEdgesRef.current=null;if(pending)onChange(pending)})}
  const flushEdgesChange=()=>{if(!pendingEdgesRef.current)return;if(edgeFrameRef.current!==null)cancelAnimationFrame(edgeFrameRef.current);edgeFrameRef.current=null;const pending=pendingEdgesRef.current;pendingEdgesRef.current=null;onChange(pending)}
  const move=(event:ReactPointerEvent)=>{const drag=dragRef.current,next=point(event);if(!drag||drag.pointer!==event.pointerId||!next)return;const opening=edges[drag.side];if(!opening)return;const isInner=drag.handle.startsWith('inner'),isTop=drag.handle.endsWith('Top');let min=-Infinity,max=Infinity;if(drag.side==='left'){max=isInner?(isTop?door.topLeft.x:door.bottomLeft.x)-.006:(isTop?opening.innerTop.x:opening.innerBottom.x)-.02}else{min=isInner?(isTop?door.topRight.x:door.bottomRight.x)+.006:(isTop?opening.innerTop.x:opening.innerBottom.x)+.02}const requested={x:Math.max(min,Math.min(max,next.x)),y:next.y},quad=sideliteQuadrilateral(drag.side,opening),snapped=freeDragWithMagneticSnap(quad,drag.corner,requested,size,snapRef.current,event.shiftKey,{x:[door.topLeft.x,door.topRight.x,door.bottomLeft.x,door.bottomRight.x],y:[door.topLeft.y,door.topRight.y,door.bottomLeft.y,door.bottomRight.y]});snapRef.current=snapped.state;setSnapGuides(snapped.guides);setAlignedEdges(current=>{const sideEdges=new Set(current[drag.side]),cornerIndex=CORNER_ORDER.indexOf(drag.corner),previousEdge=(cornerIndex+3)%4;sideEdges.delete(cornerIndex);sideEdges.delete(previousEdge);if(snapped.state.primary==='previous')sideEdges.add(previousEdge);if(snapped.state.primary==='next')sideEdges.add(cornerIndex);if(snapped.state.secondary){sideEdges.add(previousEdge);sideEdges.add(cornerIndex)}return{...current,[drag.side]:sideEdges}});const updated={...quad,[drag.corner]:snapped.point};if(!isValidEntranceCorners(updated))return;scheduleEdgesChange({...edges,[drag.side]:drag.side==='left'?{outerTop:updated.topLeft,innerTop:updated.topRight,innerBottom:updated.bottomRight,outerBottom:updated.bottomLeft}:{innerTop:updated.topLeft,outerTop:updated.topRight,outerBottom:updated.bottomRight,innerBottom:updated.bottomLeft}})}
  const moveMagnifier=(event:ReactPointerEvent<HTMLButtonElement>)=>{if(magnifierDragRef.current!==event.pointerId)return;const bounds=editorRef.current?.getBoundingClientRect();if(!bounds)return;const insetX=Math.min(.45,magnifierSize/2/Math.max(1,bounds.width)),insetY=Math.min(.45,magnifierSize/2/Math.max(1,bounds.height));setMagnifierPosition({x:Math.max(insetX,Math.min(1-insetX,(event.clientX-bounds.left)/bounds.width)),y:Math.max(insetY,Math.min(1-insetY,(event.clientY-bounds.top)/bounds.height))})}
  const endMagnifierDrag=(event:ReactPointerEvent<HTMLButtonElement>)=>{if(magnifierDragRef.current!==event.pointerId)return;if(event.currentTarget.hasPointerCapture(event.pointerId))event.currentTarget.releasePointerCapture(event.pointerId);magnifierDragRef.current=null}
  const pts=(value:EntranceCorners)=>[value.topLeft,value.topRight,value.bottomRight,value.bottomLeft].map(p=>`${p.x*size.width},${p.y*size.height}`).join(' '),doorPts=pts(door)
  const doorTop=Math.min(door.topLeft.y,door.topRight.y),doorBottom=Math.max(door.bottomLeft.y,door.bottomRight.y)
  const handles = !showSideChoice ? sides.flatMap((side) => {
    const opening = edges[side]
    if (!opening) return []
    return (['innerTop','innerBottom','outerTop','outerBottom'] as Handle[]).map((handle) => (
      <button key={`${side}-${handle}`} type="button" className={`sidelite-edge-handle ${handle.startsWith('inner')?'inner':''} ${(()=>{const cornerIndex=CORNER_ORDER.indexOf(cornerForHandle(side,handle));return alignedEdges[side].has(cornerIndex)||alignedEdges[side].has((cornerIndex+3)%4)})()?'aligned':''}`} aria-label={`Move ${side} sidelite ${handle}`} style={{left:`${opening[handle].x*100}%`,top:`${opening[handle].y*100}%`}} onPointerDown={(event)=>{event.preventDefault();stageRef.current?.setPointerCapture(event.pointerId);const corner=cornerForHandle(side,handle);dragRef.current={side,handle,pointer:event.pointerId,corner};snapRef.current=emptySnapState();setActiveHandle({side,handle})}}/>
    ))
  }) : []
  const magnifiedPoint=activeHandle?edges[activeHandle.side]?.[activeHandle.handle]:null
  return <><div ref={editorRef} className="visualizer-editor sidelite-editor">
    {magnifiedPoint&&size.width>0&&<button type="button" className="entrance-point-magnifier" aria-label="Drag to move the sidelite corner magnifier" style={{width:magnifierSize,height:magnifierSize,left:`${magnifierPosition.x*100}%`,top:`${magnifierPosition.y*100}%`,bottom:'auto',backgroundImage:`url(${JSON.stringify(imageSrc)})`,backgroundSize:`${size.width*MAGNIFIER_ZOOM}px ${size.height*MAGNIFIER_ZOOM}px`,backgroundPosition:`${magnifierSize/2-magnifiedPoint.x*size.width*MAGNIFIER_ZOOM}px ${magnifierSize/2-magnifiedPoint.y*size.height*MAGNIFIER_ZOOM}px`}} onPointerDown={event=>{event.preventDefault();event.stopPropagation();event.currentTarget.setPointerCapture(event.pointerId);magnifierDragRef.current=event.pointerId}} onPointerMove={moveMagnifier} onPointerUp={endMagnifierDrag} onPointerCancel={endMagnifierDrag}><span className="entrance-magnifier-zoom">3×</span><span className="entrance-magnifier-move"><Move size={13}/></span><i/></button>}
    <div ref={stageRef} className={`entrance-image-stage sidelite-stage ${zoom>1?'photo-pan-enabled':''} ${isPanning?'photo-panning':''}`} style={size.width?{width:size.width,height:size.height,transform:`translate(${pan.x}px, ${pan.y}px) scale(${zoom})`}:undefined} onPointerDown={event=>{if(!(event.target as Element).closest('button'))beginPan(event)}} onPointerMove={event=>{if(!movePan(event))move(event)}} onPointerUp={event=>{endPan(event);flushEdgesChange();dragRef.current=null;snapRef.current=emptySnapState();setSnapGuides({})}} onPointerCancel={event=>{endPan(event);flushEdgesChange();dragRef.current=null;snapRef.current=emptySnapState();setSnapGuides({})}} onWheel={onWheel}>
      <img src={imageSrc} alt="Uploaded entrance for sidelite placement" onLoad={event=>{naturalRef.current={width:event.currentTarget.naturalWidth,height:event.currentTarget.naturalHeight};resize()}}/>
      {size.width>0&&<svg className="sidelite-selection-svg" viewBox={`0 0 ${size.width} ${size.height}`}><polygon className="sidelite-door-confirmed" points={doorPts}/>{dividerJambQuads(door,edges).map((quad,index)=><polygon key={`d${index}`} className="sidelite-divider-region" points={pts(quad)}/>)}{(['left','right']as SideliteSide[]).map(side=>{const opening=edges[side];if(!opening)return null;const quad=sideliteQuadrilateral(side,opening),points=CORNER_ORDER.map(id=>quad[id]);return <g key={side}><polygon className="sidelite-region sidelite-region-feedback" points={pts(quad)}/>{points.map((point,index)=>{const next=points[(index+1)%4];return <line key={index} className={`sidelite-connection-edge ${alignedEdges[side].has(index)?'aligned':''}`} x1={point.x*size.width} y1={point.y*size.height} x2={next.x*size.width} y2={next.y*size.height}/>})}</g>})}{snapGuides.x!==undefined&&<line className="magnetic-snap-guide" x1={snapGuides.x*size.width} y1="0" x2={snapGuides.x*size.width} y2={size.height}/>} {snapGuides.y!==undefined&&<line className="magnetic-snap-guide" x1="0" y1={snapGuides.y*size.height} x2={size.width} y2={snapGuides.y*size.height}/>} {snapGuides.line&&<line className="magnetic-snap-guide" x1={snapGuides.line[0].x*size.width} y1={snapGuides.line[0].y*size.height} x2={snapGuides.line[1].x*size.width} y2={snapGuides.line[1].y*size.height}/>}</svg>}
      {showSideChoice&&<><button type="button" className="sidelite-side-zone sidelite-side-zone-left" style={{left:0,top:`${doorTop*100}%`,width:`${Math.max(.12,Math.min(door.topLeft.x,door.bottomLeft.x))*100}%`,height:`${Math.max(.2,doorBottom-doorTop)*100}%`}} onClick={()=>onChooseSide?.('left')}><span>Left</span><small>Left of Door</small></button><button type="button" className="sidelite-side-zone sidelite-side-zone-right" style={{right:0,top:`${doorTop*100}%`,width:`${Math.max(.12,1-Math.max(door.topRight.x,door.bottomRight.x))*100}%`,height:`${Math.max(.2,doorBottom-doorTop)*100}%`}} onClick={()=>onChooseSide?.('right')}><span>Right</span><small>Right of Door</small></button></>}
      {handles}
    </div>
    <div className="visualizer-zoom-controls" role="group" aria-label="Uploaded photo zoom controls"><button type="button" aria-label="Zoom uploaded photo out" disabled={zoom<=1} onClick={zoomOut}><ZoomOut size={17}/></button><span aria-live="polite">{Math.round(zoom*100)}%</span><button type="button" aria-label="Zoom uploaded photo in" disabled={zoom>=4} onClick={zoomIn}><ZoomIn size={17}/></button><button type="button" onClick={resetZoom}>Reset Zoom</button></div>
  </div><div className="visualizer-zoom-controls mobile-external-zoom-controls" role="group" aria-label="Uploaded photo zoom controls"><button type="button" aria-label="Zoom uploaded photo out" disabled={zoom<=1} onClick={zoomOut}><ZoomOut size={17}/></button><span aria-live="polite">{Math.round(zoom*100)}%</span><button type="button" aria-label="Zoom uploaded photo in" disabled={zoom>=4} onClick={zoomIn}><ZoomIn size={17}/></button><button type="button" onClick={resetZoom}>Reset Zoom</button></div></>
}

export type ProductLayer={kind:'assembled-entry';corners:EntranceCorners;sourceRect:{x:number;y:number;width:number;height:number};flipX?:boolean}
export function productLayers(_door:EntranceCorners,_edges:SideliteEdges,_sourceSides:SideliteSide[],outerFrame:EntranceCorners,flipDoor=false,_doorLeafCount:1|2=1):ProductLayer[]{
  // DoorFrame has already assembled and flattened the complete rectangular
  // elevation. Preserve its straight frame, equal mullions, shared baseline,
  // glass, and hardware by applying exactly one full-source homography.
  return [{kind:'assembled-entry',corners:outerFrame,sourceRect:{x:0,y:0,width:1,height:1},flipX:flipDoor}]
}
